  apiVersion: traefik.io/v1alpha1
  kind: IngressRoute
  metadata:
    annotations:
      meta.helm.sh/release-name: voting
      meta.helm.sh/release-namespace: voting
    generation: 1
    labels:
      app.kubernetes.io/instance: voting
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: voting
    name: voting
    namespace: voting
  spec:
    entryPoints:
    - web
    routes:
    - kind: Rule
      match: PathPrefix(`/voting-service`)
      services:
      - kind: Service
        name: voting
        namespace: voting
        passHostHeader: true
        port: 8080

